#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                102
#define IDD_JOYST_IMM                           103
#define IDR_ACCELERATOR1                        103
#define IDC_AXES                                1010
#define IDC_AXIS_1                              IDC_AXES
#define IDC_AXIS_2                              1011
#define IDC_AXIS_3                              1012
#define IDC_AXIS_4                              1013
#define IDC_AXIS_5                              1014
#define IDC_AXIS_6                              1015
#define IDC_AXIS_7                              1016
#define IDC_AXIS_8                              1017
#define IDC_AXIS_TEXTS                          1020
#define IDC_AXIS_1_TEXT                         IDC_AXIS_TEXTS
#define IDC_AXIS_2_TEXT                         1021
#define IDC_AXIS_3_TEXT                         1022
#define IDC_AXIS_4_TEXT                         1023
#define IDC_AXIS_5_TEXT                         1024
#define IDC_AXIS_6_TEXT                         1025
#define IDC_AXIS_7_TEXT                         1026
#define IDC_AXIS_8_TEXT                         1027
#define IDC_POV_TEXTS                           1030
#define IDC_POV0_TEXT                           IDC_POV_TEXTS
#define IDC_POV1_TEXT                           1031
#define IDC_POV2_TEXT                           1032
#define IDC_POV3_TEXT                           1033
#define IDC_POVS                                1040
#define IDC_POV0                                IDC_POVS
#define IDC_POV1                                1041
#define IDC_POV2                                1042
#define IDC_POV3                                1043
#define IDC_BUTTON_BOX                          1044
#define IDC_BUTTONS                             1045
#define IDC_BUTTON1                             IDC_BUTTONS
#define IDC_BUTTON2                             1046
#define IDC_BUTTON3                             1047
#define IDC_BUTTON4                             1048
#define IDC_BUTTON5                             1049
#define IDC_BUTTON6                             1050
#define IDC_BUTTON7                             1051
#define IDC_BUTTON8                             1052
#define IDC_BUTTON09                            1053
#define IDC_BUTTON10                            1054
#define IDC_BUTTON11                            1055
#define IDC_BUTTON12                            1056
#define IDC_BUTTON13                            1057
#define IDC_BUTTON14                            1058
#define IDC_BUTTON15                            1059
#define IDC_BUTTON16                            1060
#define IDC_BUTTON17                            1061
#define IDC_BUTTON18                            1062
#define IDC_BUTTON19                            1063
#define IDC_BUTTON20                            1064
#define IDC_BUTTON21                            1065
#define IDC_BUTTON22                            1066
#define IDC_BUTTON23                            1067
#define IDC_BUTTON24                            1068
#define IDC_BUTTON25                            1069
#define IDC_BUTTON26                            1070
#define IDC_BUTTON27                            1071
#define IDC_BUTTON28                            1072
#define IDC_BUTTON29                            1073
#define IDC_BUTTON30                            1074
#define IDC_BUTTON31                            1075
#define IDC_BUTTON32                            1076
